[+] new cstyle check & delete char in buff & banned function finder

diff --git a/.github/workflows/project_tester.yml b/.github/workflows/project_tester.yml
--- a/.github/workflows/project_tester.yml
+++ b/.github/workflows/project_tester.yml
@@ -30,7 +30,7 @@ jobs:
           if [ -s coding-style-reports.log ]; then
             exit 1
           fi
-  
+
   check_program_compilation:
     runs-on: ubuntu-latest
     container:
@@ -53,3 +53,29 @@ jobs:
               exit 1
             fi
           done
+
+  check_banned_functions:
+    runs-on: ubuntu-latest
+    needs: check_program_compilation
+    container:
+      image: ghcr.io/epitech/coding-style-checker:latest
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v3
+      - name: Banned function checker
+        run: |
+          make
+          objdump -T 42sh | grep '      DF' > banned-functions.log \
+          while read Line; \
+          do \
+          LIBU=$(echo $Line | cut -d' ' -f9); \
+          FUNC=$(echo $Line | cut -d' ' -f10); \
+          LIBC=${LIBU:1:5} \
+          LIBN=${LIBU:1:7} \
+          if [ "$LIBC" != "GLIBC" ]; then
+            if [ "$LIBN" != "NCURSES" ]; then
+              echo "::error:: $FUNC is a banned function";
+              exit 1;
+            fi
+          fi
+          done < banned-functions.log
