[+] add banned function checker to the auto tester & better make cstyle & added a basic scroll on term
* [+] adding scroll but lines disappear

* [+] new cstyle check & delete char in buff & banned function finder

* [~] try fixing error on compilation

* [~] fix syntax error

* [~] sometimes make just don't want to compile everything

* [~] try not to re compile

* [~] still have problems with make

* [~] try to make only one time

* [~] add ; in the script

* [~] find why there is a banned function

* [~] display banned-function.log

* [~] fix bad parsing

* [~] output line

* [~] print full output and remove exit

* [~] re add exit 1

diff --git a/.github/workflows/project_tester.yml b/.github/workflows/project_tester.yml
--- a/.github/workflows/project_tester.yml
+++ b/.github/workflows/project_tester.yml
@@ -30,7 +30,7 @@ jobs:
           if [ -s coding-style-reports.log ]; then
             exit 1
           fi
-  
+
   check_program_compilation:
     runs-on: ubuntu-latest
     container:
@@ -53,3 +53,22 @@ jobs:
               exit 1
             fi
           done
+      - name: Banned function checker
+        run: |
+          objdump -T $EXECUTABLES | grep '    DF ' > banned-functions.log
+          while read Line; \
+          do \
+          LIBU=$(echo $Line | cut -d' ' -f5); \
+          FUNC=$(echo $Line | cut -d' ' -f6); \
+          LIBC=${LIBU:0:5}; \
+          LIBN=${LIBU:0:7}; \
+          JSP=${LIBU:0:4}; \
+          if [ "$LIBC" != "GLIBC" ]; then
+            if [ "$LIBN" != "NCURSES" ]; then
+              if [ "$JSP" != "Base" ]; then
+                echo "::error:: $FUNC is a banned function";
+                exit 1;
+              fi
+            fi
+          fi
+          done < banned-functions.log
